# Training Hyperparameters
training_args:
  overwrite_output_dir: True
  num_train_epochs: 20
  train_batch_size: 8
  eval_batch_size: 8
  gradient_accumulation_steps: 2
  bf16: False
  fp16: False
  learning_rate: 0.00002
  eval_steps: 100
  save_steps: 100
  save_total_limit: 2
  logging_steps: 50
  load_best_model_at_end: True
  metric_for_best_model: "f1"

  
