# Training Hyperparameters
training_args:
  overwrite_output_dir: True
  num_train_epochs: 5
  train_batch_size: 8
  eval_batch_size: 8
  gradient_accumulation_steps: 4
  learning_rate: 0.00002
  eval_steps: 100
  save_steps: 100
  save_total_limit: 2
  logging_steps: 50

  


  
